package com.junkworld.game;

public enum CurrentItemOfSlot1 {
	NONE, BOMB, FLYSWATTER, ICEFLAKE, ELECTRIC_ZAPPER, ACCELERATOR, ACCELERATOR_X, STEEL_FLYSWATTER, GLUE, ITEM_RESTORE, SUPER_GLUE, WIND_VANE, SWITCH_MACHINE, 
	AUGMENTED_BURST, STICKER, LOCKED
}
