package com.junkworld.game;

public enum CurrentSelectedItem {
	BOMB, GLUE, ICEFLAKE, SWITCH_MACHINE, AUGMENTED_BURST, STICKER, ELECTRIC_ZAPPER, ACCELERATOR, ACCELERATOR_X, STEEL_FLYSWATTER, ITEM_RESTORE, SUPER_GLUE,
	WIND_VANE,  FLYSWATTER, NONE
}
